import React from 'react';
import Head from 'next/head';

interface IProps {
  title: string;
}

const Header = (props: IProps) => {
  const { title } = props;
  return (
    <Head>
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default Header;
